### ISSUE TITLE
iOS app for iOS-Goodies

### ISSUE THREAD

**Issue by sanketfirodiya** [iOS-Goodies/iOS-Goodies#1050]
Have you guys thought about building an app to deliver the articles each week?

As a reader I think it would be useful to have all these articles in one place, that's searchable, sorted by topics and available offline.

Would love to help out with building it too of course.

**Comment by mariusc** [comment]
iOS Goodies started as a newsletter, and our main focus right now is to keep delivering high-quality articles every Thursday to our subscribers. We don't have the time to build an app for it right now. 

However, if anyone from the community wants to start building a 3rd party one, we would be happy for that. 

As far as I see it, one of the initial steps would be getting the data. At the moment, I see two ways of doing that: 

- from the website: iOS Goodies is actually a tumblr page, and one can probably use the tumblr API to get all the posts
- from the RSS feed: http://ios-goodies.com/rss

If anyone wants to make a 3rd party app for reading iOS Goodies newsletters, I'll try to offer some advice if needed, as much as time allows.

**Comment by sanketfirodiya** [comment]
Cool, thanks @mariusc!
Closing for now, will reopen if I decide to take a lead on this.
