### ISSUE TITLE
Terminal app

### ISSUE THREAD

**Issue by FranciscoAmado** [iOS-Goodies/iOS-Goodies#1103]
Hi there!

[Terminal](https://github.com/louisdh/terminal) is an app working as a sandboxed terminal.
Since this is an App targeted to developers and open-sourced, we could feature this in one of iOSGoodies issues.

Let me know what you think.
Cheers 🍪

**Comment by mariusc** [comment]
I think we can add it in the Tools section since it's an open source iOS project. The code could be interesting :)

**Comment by mariusc** [comment]
Done :)
