### ISSUE TITLE
Article in issue 318 link does not match the title or author

### ISSUE THREAD

**Issue by joshuajhomann** [iOS-Goodies/iOS-Goodies#1792]
The item `Getting Started with RxSwift and RxCocoa by @goktuggumus` actually links to `Everything you need to know about Memory Leaks in iOS by Ali Akhtar`.  I'm not clear if the intent was to include one or the other or both of these articles, so I can't open a PR for a fix.

**Comment by mariusc** [comment]
Oh, thanks for pointing that out, I hadn't noticed. I'll ask Lisa who submitted the article.

**Comment by mariusc** [comment]
Thanks again for pointing this out. I just sent out this week's edition of iOS Goodies. I'll close this issue now.
