### ISSUE TITLE
Version PT-Br?

### ISSUE THREAD

**Issue by Viniciuscarvalho** [iOS-Goodies/iOS-Goodies#1807]
Hi, @mariusc and all,
I’ve been following goodies for a long time and this year I intend to start helping curate interesting links and be a maintainer.
In addition, I was wondering if it would be possible to translate the newsletter into Brazilian Portuguese where not everyone can follow content in English. I am available to do this weekly translation and have a PT-Br version.

**Comment by mariusc** [comment]
Hi,
Thanks for the nice words. Looking forward to your contributions on the newsletter :)

Regarding translating the newsletter into Brazilian Portuguese, I'll need to think a bit more about it. My first thought was "Yes, let's do this so more people can benefit from it". But then I realised it's not that easy. Some concerns I have currently:
1. The newsletter is mostly a collection of links. I write a comment at the beginning of each edition, but that's not too much, and I doubt it's the main reason people read the newsletter. So unless we translate the content of the linked articles, it wouldn't be too useful
2. I'll need to look into if and how it would be possible for the subscribers to choose which version of the newsletter they want to subscribe to (English or Brazilian-Portuguese). This goes for current subscribers (offer a link for them to subscribe to the other language version?) and for future subscribers (sign up form should give a language choice). 
3. I imagine you would need 1-2 days to make the Brazilian-Portuguese version. I send the newsletter on Thursday evenings (CET time). If we are to send both versions at the same time, I'd need to "freeze" the current edition on Wednesday morning, to give you time to work on the PT-Br version.

I'll need to think a bit more about the possible implications and the best way to do this. Maybe also get some other opinions. I'll get back to you.

**Comment by Viniciuscarvalho** [comment]
Hi,
I believe that this question of language choice is possible through a choice of the link where the person wants to have the language of the newsletter, no? Today for English and a link only to the Portuguese version.

I believe it would take a day or half to review the content and translate it into Portuguese. I believe that on Thursday or Friday morning I would be able to revise the entire content, since you would have already curated the content.

It was even a suggestion to contribute more and also help in some way.

I will try to send some links every week without a doubt. 👍

**Comment by rbarbosa** [comment]
My 2 cents...and I'm a Portuguese guy.
I agree 100% with @mariusc. Although I like Marius' introductions, they are really small and doesn't make sense to translate the introduction. 
I also suspect that most, if not all, of the subscribers, can read English as it's the lingua franca for developers.
So, translating the content would be only that small text.
Also, as Marius referred, the amount of work would be enormous versus the return.

**Comment by mariusc** [comment]
Yeah, I've also given this a bit ore thought, and while I'm a fan of internationalization and localization, I think overall there would be a lot more benefit for the community if you would help translate other sources of information. Here are some well known projects that have great content and are open to translating in other languages:
- Paul Hudson's (@twostraws) [Hacking with Swift](https://www.hackingwithswift.com/): [translation repo](https://github.com/twostraws/HWSTranslation)
- Mattt's (@mattt) [NSHipster](https://nshipster.com/): I see [repos for various languages here](https://github.com/NSHipster?q=articles&type=&language=). Couldn't easily find a way to get started with another language, so I'd recommend you contact Mattt ([https://witter.com/nshipster](https://twitter.com/nshipster), [https://twitter.com/mattt](https://twitter.com/mattt)) or open an issue to [https://github.com/NSHipster/articles](https://github.com/NSHipster/articles)

Really hope that us saying "no, thanks" here won't curb your enthusiasm. I will close this issue now, but if you have questions or just want to submit other articles to iOS Goodies, please feel free to do it.
