### ISSUE TITLE
About Week 340, missing the tool I added.

### ISSUE THREAD

**Issue by muukii** [iOS-Goodies/iOS-Goodies#1998]
Sorry for the trouble with you.
In https://github.com/iOS-Goodies/iOS-Goodies/blob/master/Issues/Week340.md
It seems it lost the tool what I added that is Verge.
What something's happened?

**Comment by mariusc** [comment]
Hi! Sorry for the late answer, needed some time off after last week :). As also mentioned in the contributing guidelines, a merged pull request doesn't guarantee the proposed link will make it into the newsletter. In this case, the reasons were that last week's edition had a lot of links already and that Verge was also featured in Issue 335 https://ios-goodies.com/post/618734968651350016/week-335

**Comment by muukii** [comment]
@mariusc 
Thanks! Sorry my understanding was wrong.
Yes, you're right, Verge has been featured in the list of articles.
I'm sorry bothering you.

**Comment by mariusc** [comment]
No problem :)
