### ISSUE TITLE
Missing article Week 402

### ISSUE THREAD

**Issue by abadikaka** [iOS-Goodies/iOS-Goodies#2455]
Hi @mariusc and @dkhamsing  , it turns out my article did not make it into the week 402 newsletter (I acknowledge if my article maybe will not be in the newsletter)
https://michaelabadi.com/articles/create-calendar-view-swiftui/

I am asking because I created this article after people were interested in my approach to solve this UI in my [tweet](https://twitter.com/michaelabadiii/status/1434537089157132288?s=20) and [tweet2](https://twitter.com/michaelabadiii/status/1433812643886755841?s=20). and I would like to share how I did it with more readers.
Is there any specific reason I did not make it? Any feedback makes me feel much better and not feel sad :D. Feedback appreciated so I can do better on the next article 🙏.

Thank you.
Michael

**Comment by mariusc** [comment]
Hey Michael,

Thanks for reaching out. Indeed, the article didn't make it into the newsletter. There were a lot of very good articles last week and unfortunately not all of them could make it into the newsletter. I hope you don't feel discouraged by the fact that your article didn't make it this time. 
The reason I chose to not include the article was that I'm not a big fan of tutorial-like articles with a lot of source code. I prefer articles with more text, describing a problem and an approach to solve it, and not articles where the reader can copy-paste the code and get to the same result as the author. I realise this is probably not the feedback you're hoping to hear. In the end, the curation process is subjective. I'm choosing the links that make it into the newsletter and what may be interesting to me may not be interesting to other readers, and the other way around. And sometimes I'm wrong and sometimes I'm not, but there's just no simple way to have a hand-curated newsletter without sometimes making some hard decisions
Again, I hope this doesn't discourage you from creating content and sharing it with the community.
Keep up the good work 👍

**Comment by abadikaka** [comment]
sure. thank you for the feedback! @mariusc
