### ISSUE TITLE
Question about eligibility

### ISSUE THREAD

**Issue by philipturner** [iOS-Goodies/iOS-Goodies#2503]
I created [ARHeadsetKit](https://github.com/philipturner/ARHeadsetKit), a high-level framework for experimenting with AR and making AR headset experiences affordable ($5 vs. the $3500 Microsoft Hololens). After spending [2000+ hours](https://philipturner.github.io/first-affordable-ar-headset) on it myself (that's not a typo), I wanted to share it with as many people as possible. However, no matter how many people I reach out to, almost nobody responds. I have a massive barrier to spreading information about this, so I would like to participate in this newsletter.

I recently released hours worth of ARHeadsetKit tutorial content (see "Tutorial Series" on the README), which took me dozens of hours of elapsed time to make. From the three people who have tried them so far, I had immensely positive reactions. They are very similar to Apple's SwiftUI tutorials. I'm wondering if you could try them out yourself, and find a way to ask others to in your newsletter.

In addition to qualifying as an `Article`, my experience could fall under the `Business/Career` category, because I learned the harsh reality of having high expectations for a personal open-source framework.

It would be perfect if @mariusc highlighted ARHeadsetKit in the intro for a weekly letter. That would be an insane help, but it's probably too much to ask for.

Are you open to considering ARHeadsetKit for the newsletter?

**Comment by mariusc** [comment]
Hi Philip! Thank you for reaching out. I will look into it and consider it for next week's edition.

**Comment by philipturner** [comment]
Awesome! I recommend reading [my article](https://philipturner.github.io/first-affordable-ar-headset) (15-minute read) before posting. If you have time, I also recommend doing a few of its tutorials.

I'm also working on [GPU acceleration](https://github.com/dl4s-contributors/dl4s-evolution) for [DL4S](https://github.com/palle-k/DL4S), the successor to Swift for TensorFlow. When it's finished in a few months, I think that would make a great article as well.

**Comment by mariusc** [comment]
I've included it in this week's edition :)
