### ISSUE TITLE
Broken link in Issue 73

### ISSUE THREAD

**Issue by dkhamsing** [iOS-Goodies/iOS-Goodies#61]
http://gregoryszorc.com/blog/2015/03/28/notes-from-facebook
should be 
http://gregoryszorc.com/blog/2015/03/28/notes-from-facebook's-developer-infrastructure-at-scale-f8-talk/

**Comment by 3lvis** [comment]
Doesn't seem broken anymore.

* [Notes from Facebook's Developer Infrastructure at Scale F8 Talk](http://gregoryszorc.com/blog/2015/03/28/notes-from-facebook%27s-developer-infrastructure-at-scale-f8-talk/), by [@indygreg](https://twitter.com/indygreg)

**Comment by RuiAAPeres** [comment]
@dkhamsing if you find a broken link, please make a pull request, we will then review it.

**Comment by dkhamsing** [comment]
The link is broken on iOS goodies . com

**Comment by dkhamsing** [comment]
@RuiAAPeres the link is broken on http://ios-goodies.com/post/115307908221/week-73

**Comment by dkhamsing** [comment]
cc @tiagoalmeida

**Comment by RuiAAPeres** [comment]
@dkhamsing fixed! :cake:

**Comment by dkhamsing** [comment]
Cheers
